### ISSUE TITLE
express server build failing

### ISSUE THREAD

**Issue by tulsi-prasad** [tulsi-prasad/pleonasma-io#1]
The server running on express is set few hours ago by me. I have tried running ```node index.js``` several times but got different issues over time. I am quite afraid this maybe due to the file structure of the project. I would love to see PRs regarding the build setup by fixing the express server and adding correct path for the react components.

**Comment by ezesundayeze** [comment]
Can this issue be reproduced?
What is your file structure
What have you tried? 
Please, can you provide more details --- stack trace, logs, code you've tried, etc?

**Comment by tulsi-prasad** [comment]
Hey @ezesundayeze, glad to hear from you. Here's what happening in a nutshell.

### Describe the bug

After setting up the dependencies and server in the **src/server/index.js** as follows, when we run the index.js file we get the following errors: 
```
import React from "react";
^^^^^^

SyntaxError: Cannot use import statement outside a module
?[90m    at Module._compile (internal/modules/cjs/loader.js:895:18)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:815:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:727:14)?[39m
?[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)?[39m
?[90m    at internal/main/run_main_module.js:17:11?[39m
```

This is the main backend code, index.js.
```
import React from "react";
import ReactDOM from "react-dom";

const express = require("express");
const bodyParser = require("body-parser");
const ejs = require("ejs");
const path = require("path");
const app = express();

app.use(
    bodyParser.urlencoded({
        extended: true
    })
);

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

app.use(express.static(path.join(__dirname, 'public')));

// Decide the port to listen
let port = process.env.PORT;

if(port == null || port == "") {
    port = 3000;
}

import App from "../components/App";
ReactDOM.render(<App />, document.getElementById("root"));

app.listen(port, function() {
    console.log("Server started at port 3000");
});
```

### Expected behaviour
After running ```node index.js``` we shall render **Hello World** on `localhost: 3000` which will tell  our app is running correctly.

### To reproduce the behaviour
```
cd src/server
node index.js
```
### File structure of the project is as follows:
```
Pleonasma
 |
 +-- node_modules
 |    
 +-- public
 |  |  
 |  +-- css
 |  +-- scss
 +-- src
 |  |  
 |  +-- components
 |  |  +-- App.jsx
 |  +-- server
 |  |  +-- index.js
 +-- views
 |  +-- index.ejs
 +-- .gitignore, package.json, yarn.lock, etc
```
**If the above is unclear this diagram below will make things easier**

![Annotation 2019-12-13 234626](https://user-images.githubusercontent.com/52394293/70822146-d3c6a400-1e02-11ea-8ccc-f5dec3cc7c20.png)


I wonder where the things go exactly wrong, is that the file structure or some path where it's going wrong. That's making the build fail.

**Comment by ezesundayeze** [comment]
Hey @tulsi-prasad, nice information here. Just curious, any reason why you are importing react and react-dom on the backend?

> 
> This is the main backend code, index.js.
> 
> ```javascript
> import React from "react";
> import ReactDOM from "react-dom";
> 
> const express = require("express");
> const bodyParser = require("body-parser");
> const ejs = require("ejs");
> const path = require("path");
> const app = express();
```

**Comment by tulsi-prasad** [comment]
Hey @ezesundayeze 👋 

In the above **index.js** file, 
> import App from "../components/App";
> ReactDOM.render(<App />, document.getElementById("root"));
These lines use react to render the app component to the application. This **root** *id* refers to the div in `views/index.ejs` file to which all the react code is exported.

**Comment by ankitjena** [comment]
@tulsi-prasad sadly nodejs still runs es5. So the `import` statement there is es6. Either change that to `require` or use Babel so that you can run es6. [https://www.robinwieruch.de/minimal-node-js-babel-setup](https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.robinwieruch.de/minimal-node-js-babel-setup/&ved=2ahUKEwjL3LGzlbTmAhXcFjQIHRtIDBwQFjACegQIAhAB&usg=AOvVaw1ObKg3VImv8RAYSlF831gF)

**Comment by tulsi-prasad** [comment]
> @tulsi-prasad sadly nodejs still runs es5. So the `import` statement there is es6. Either change that to `require` or use Babel so that you can run es6. [https://www.robinwieruch.de/minimal-node-js-babel-setup](https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.robinwieruch.de/minimal-node-js-babel-setup/&ved=2ahUKEwjL3LGzlbTmAhXcFjQIHRtIDBwQFjACegQIAhAB&usg=AOvVaw1ObKg3VImv8RAYSlF831gF)

Got this, thanks @ankitjena will update them. Is there any bot to understand this kind of issues? Although being explicit is better, but just in case. 👍

**Comment by ankitjena** [comment]
@tulsi-prasad not that I know of. But building one seems like a great idea.

**Comment by vutran6853** [comment]
If you want to have react render app from server side you. you can but you need to tell node to transform jsx code with help of  some config. It bit more work to setup. This is call Server Side render. 
if you want this.

if not. I think you use express for backend API endpoint for front-end App. 
File structure like 
root: {
 src folder:  <-- this is front-end app 
 server folder: <-- backend-API code here
}

**Comment by tulsi-prasad** [comment]
Thanks for making things clear, @vutran6853. After a bit of hardships faced in this manual method, I made a new branch [setup](https://github.com/tulsi-prasad/pleonasma-io/tree/setup) and bootstraped my react application from official `create-react-app` template in a folder **client**, so now it's working. Also **express** server is running in the backend.

Now the only difficulty, is to join both the ends and direct them to the same port. As of now, they both render at different ports. That's my agenda for today. As always, love to hear any suggestions. 👍

**Comment by tulsi-prasad** [comment]
#### Thanks for the help people. Finally got to work both the front and backend together. Hence, closing issue #1.
